import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/main.scss";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "../components/Navbar/Navbar";
import ClientLayout from "./ClientLayout";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "../lib/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryClientProvider client={queryClient}>
          <Theme
            appearance="light"
            accentColor="mint"
            grayColor="slate"
            radius="large"
            scaling="95%"
          >
            <ClientLayout>
              <Navbar />
              {children}
            </ClientLayout>
          </Theme>
        </QueryClientProvider>
      </body>
    </html>
  );
}
